---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: apache-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: apache-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: apache-exporter
    spec:
      containers:
      - name: apache-exporter
        image: bitnami/apache-exporter:0.11.0
        ports:
          - containerPort: 9117
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        livenessProbe:
          tcpSocket:
            port: 9117
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9117
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
---
kind: Service
apiVersion: v1
metadata:
  name: apache-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9117'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: apache-exporter
  ports:
  - name: apache-exporter
    protocol: TCP
    port: 9117
    targetPort: 9117