---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: jenkins-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: jenkins-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: jenkins-exporter
    spec:
      containers:
      - name: jenkins-exporter
        image: lovoo/jenkins_exporter:latest
        ports:
          - containerPort: 9118
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        livenessProbe:
          tcpSocket:
            port: 9118
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9118
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9118'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: jenkins-exporter
  ports:
  - name: jenkins-exporter
    protocol: TCP
    port: 9118
    targetPort: 9118