---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kibana-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kibana-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kibana-exporter
    spec:
      containers:
      - name: kibana-exporter
        image: chamilad/kibana-prometheus-exporter:v7.5.x.1
        args: [
          "-kibana.uri", "http://kibana:5601",
        ]
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
        ports:
          - containerPort: 9684
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        livenessProbe:
          tcpSocket:
            port: 9684
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9684
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3

---
kind: Service
apiVersion: v1
metadata:
  name: kibana-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9684'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kibana-exporter
  ports:
  - name: kibana-exporter
    protocol: TCP
    port: 9684
    targetPort: 9684